# Generated by Django 2.2.7 on 2019-11-27 16:02

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('review', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dealer_of', models.CharField(choices=[('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra')], max_length=100, verbose_name='Manufacturer')),
                ('contactName', models.CharField(max_length=30)),
                ('has_ordered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dealers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrdered', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Customers')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, max_length=7)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrdered', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Orders')),
            ],
            options={
                'verbose_name': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Products')),
            ],
            options={
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=20)),
                ('zipCode', models.CharField(max_length=20, verbose_name='Zip/Postal Code')),
                ('phone', models.PositiveIntegerField()),
                ('secondary_phone', models.PositiveIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Customers')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Dealers')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
