# Generated by Django 2.2.7 on 2019-11-29 17:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191127_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('message', models.TextField()),
            ],
        ),
    ]
