# Generated by Django 2.2.7 on 2019-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fullName',
        ),
    ]
