# Generated by Django 2.2.7 on 2019-11-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191129_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
