# Generated by Django 2.2.7 on 2019-12-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191203_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('tower', 'Tower'), ('bimini', 'Bimini'), ('gear', 'Gear'), ('board_rack', 'Board Racks'), ('accessory', 'Accessory')], default='accessory', max_length=50, verbose_name='Category'),
        ),
    ]
