# Generated by Django 2.2.7 on 2019-12-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
    ]
