# Generated by Django 2.2.7 on 2019-11-27 02:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import towers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.PositiveIntegerField(choices=[('1', 'Mastercraft'), ('2', 'Moomba'), ('3', 'Stingray'), ('4', 'Cobalt'), ('5', 'Bryant'), ('6', 'Four Winns'), ('7', 'Sea Doo'), ('8', 'Malibu'), ('9', 'Bayliner'), ('10', 'Startcraft'), ('11', 'Centurion'), ('12', 'Tige'), ('13', 'Nautique'), ('14', 'Yamaha'), ('15', 'Supra')], default=None)),
                ('start_year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year])),
                ('end_year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year])),
                ('model', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Towers',
            },
        ),
        migrations.CreateModel(
            name='TowerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('style', models.CharField(choices=[('FL', 'Fullsize'), ('MN', 'Mini')], default='Fullsize', max_length=2)),
                ('finish', models.CharField(choices=[('BRUSHED', 'Brushed'), ('POWDER_COATED', 'Powder coated'), ('POLISHED', 'Polished')], default='Brushed', max_length=20)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'TowerOrders',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.PositiveIntegerField(choices=[('1', 'Mastercraft'), ('2', 'Moomba'), ('3', 'Stingray'), ('4', 'Cobalt'), ('5', 'Bryant'), ('6', 'Four Winns'), ('7', 'Sea Doo'), ('8', 'Malibu'), ('9', 'Bayliner'), ('10', 'Startcraft'), ('11', 'Centurion'), ('12', 'Tige'), ('13', 'Nautique'), ('14', 'Yamaha'), ('15', 'Supra')], default=None)),
                ('orientation', models.PositiveSmallIntegerField(choices=[('1', 'Main'), ('2', 'Angled'), ('3', 'Back'), ('4', 'Collapsed')], default=1)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Biminis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'Biminis',
            },
        ),
        migrations.CreateModel(
            name='BiminiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'Black'), ('JR', 'Jockey Red'), ('LR', 'Logo Red'), ('OR', 'Orange'), ('BD', 'Burgandy'), ('PB', 'Pacific Blue'), ('CD', 'Concord'), ('SY', 'Sunflower Yellow'), ('TQ', 'Turquoise'), ('SB', 'Sky Blue'), ('TS', 'Toast'), ('NT', 'Natural'), ('CG', 'Cadet Grey'), ('CL', 'Charcoal Grey'), ('BR', 'Brown'), ('NY', 'Navy'), ('FG', 'Forest Green'), ('RB', 'Royal Blue'), ('TN', 'Tan'), ('PG', 'Persian Green')], default=('BK', 'Black'), max_length=20)),
                ('qty', models.IntegerField(default=1)),
                ('bimini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Biminis')),
            ],
            options={
                'verbose_name_plural': 'BiminiOrders',
            },
        ),
        migrations.CreateModel(
            name='BiminiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.PositiveIntegerField(choices=[('1', 'Mastercraft'), ('2', 'Moomba'), ('3', 'Stingray'), ('4', 'Cobalt'), ('5', 'Bryant'), ('6', 'Four Winns'), ('7', 'Sea Doo'), ('8', 'Malibu'), ('9', 'Bayliner'), ('10', 'Startcraft'), ('11', 'Centurion'), ('12', 'Tige'), ('13', 'Nautique'), ('14', 'Yamaha'), ('15', 'Supra')], default=None)),
                ('orientation', models.PositiveSmallIntegerField(choices=[('1', 'Main'), ('2', 'Angled'), ('3', 'Back'), ('4', 'Collapsed')], default=1)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Biminis')),
            ],
            options={
                'verbose_name_plural': 'BiminiImages',
            },
        ),
    ]
