# Generated by Django 2.2.7 on 2019-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerorder',
            name='name',
            field=models.CharField(default='maristar', max_length=100),
            preserve_default=False,
        ),
    ]
