# Generated by Django 2.2.7 on 2020-01-22 00:42

import django.core.validators
from django.db import migrations, models
import towers.models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0005_auto_20191203_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='manufacturer',
            field=models.CharField(choices=[('none', 'select a manufacturer'), ('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra'), ('ndt', 'NDT'), ('not_listed', 'Not Listed')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='towers',
            name='end_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='towers',
            name='manufacturer',
            field=models.CharField(choices=[('none', 'select a manufacturer'), ('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra'), ('ndt', 'NDT'), ('not_listed', 'Not Listed')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='towers',
            name='start_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year]),
        ),
    ]
